{
  "networks": {
    "default": {
      "name": "apm-integration-testing"
    }
  },
  "services": {
    "apm-server": {
      "cap_add": [
        "CHOWN",
        "DAC_OVERRIDE",
        "SETGID",
        "SETUID"
      ],
      "cap_drop": [
        "ALL"
      ],
      "command": [
        "apm-server",
        "-e",
        "--httpprof",
        ":6060",
        "-E",
        "apm-server.rum.enabled=true",
        "-E",
        "apm-server.rum.event_rate.limit=1000",
        "-E",
        "apm-server.host=0.0.0.0:8200",
        "-E",
        "apm-server.read_timeout=1m",
        "-E",
        "apm-server.shutdown_timeout=2m",
        "-E",
        "apm-server.write_timeout=1m",
        "-E",
        "logging.json=true",
        "-E",
        "logging.metrics.enabled=false",
        "-E",
        "setup.template.settings.index.number_of_replicas=0",
        "-E",
        "setup.template.settings.index.number_of_shards=1",
        "-E",
        "setup.template.settings.index.refresh_interval=1ms",
        "-E",
        "monitoring.elasticsearch=true",
        "-E",
        "monitoring.enabled=true",
        "-E",
        "apm-server.instrumentation.enabled=true",
        "-E",
        "apm-server.instrumentation.profiling.cpu.enabled=true",
        "-E",
        "apm-server.instrumentation.profiling.heap.enabled=true",
        "-E",
        "apm-server.mode=experimental",
        "-E",
        "apm-server.kibana.enabled=true",
        "-E",
        "apm-server.kibana.host=kibana:5601",
        "-E",
        "apm-server.agent.config.cache.expiration=30s",
        "-E",
        "apm-server.kibana.username=apm_server_user",
        "-E",
        "apm-server.kibana.password=changeme",
        "-E",
        "apm-server.jaeger.http.enabled=true",
        "-E",
        "apm-server.jaeger.http.host=0.0.0.0:14268",
        "-E",
        "apm-server.jaeger.grpc.enabled=true",
        "-E",
        "apm-server.jaeger.grpc.host=0.0.0.0:14250",
        "-E",
        "output.elasticsearch.hosts=[\"http://elasticsearch:9200\"]",
        "-E",
        "output.elasticsearch.username=apm_server_user",
        "-E",
        "output.elasticsearch.password=changeme",
        "-E",
        "output.elasticsearch.enabled=true",
        "-E",
        "output.elasticsearch.pipelines=[{pipeline: 'apm'}]",
        "-E",
        "apm-server.register.ingest.pipeline.enabled=true"
      ],
      "container_name": "localtesting_7.12.0_apm-server",
      "depends_on": {
        "elasticsearch": {
          "condition": "service_healthy"
        },
        "kibana": {
          "condition": "service_healthy"
        }
      },
      "environment": [
        "BEAT_STRICT_PERMS=false"
      ],
      "healthcheck": {
        "interval": "10s",
        "retries": 12,
        "test": [
          "CMD",
          "curl",
          "--write-out",
          "'HTTP %{http_code}'",
          "-k",
          "--fail",
          "--silent",
          "--output",
          "/dev/null",
          "http://localhost:8200/"
        ]
      },
      "image": "docker.elastic.co/apm/apm-server:7.12.0",
      "labels": [
        "co.elastic.apm.stack-version=7.12.0"
      ],
      "logging": {
        "driver": "json-file",
        "options": {
          "max-file": "5",
          "max-size": "2m"
        }
      },
      "ports": [
        "127.0.0.1:8200:8200",
        "127.0.0.1:6060:6060",
        "127.0.0.1:14268:14268",
        "127.0.0.1:14250:14250"
      ]
    },
    "elasticsearch": {
      "container_name": "localtesting_7.12.0_elasticsearch",
      "environment": [
        "bootstrap.memory_lock=true",
        "cluster.name=docker-cluster",
        "cluster.routing.allocation.disk.threshold_enabled=false",
        "discovery.type=single-node",
        "path.repo=/usr/share/elasticsearch/data/backups",
        "ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g",
        "path.data=/usr/share/elasticsearch/data/7.12.0",
        "xpack.security.authc.anonymous.roles=remote_monitoring_collector",
        "xpack.security.authc.realms.file.file1.order=0",
        "xpack.security.authc.realms.native.native1.order=1",
        "xpack.security.authc.token.enabled=true",
        "xpack.security.authc.api_key.enabled=true",
        "xpack.security.enabled=true",
        "xpack.license.self_generated.type=trial",
        "xpack.monitoring.collection.enabled=true"
      ],
      "healthcheck": {
        "interval": "20",
        "retries": 10,
        "test": [
          "CMD-SHELL",
          "curl -s -k http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"
        ]
      },
      "image": "docker.elastic.co/elasticsearch/elasticsearch:7.12.0",
      "labels": [
        "co.elastic.apm.stack-version=7.12.0",
        "co.elastic.metrics/module=elasticsearch",
        "co.elastic.metrics/metricsets=node,node_stats",
        "co.elastic.metrics/hosts=http://$${data.host}:9200"
      ],
      "logging": {
        "driver": "json-file",
        "options": {
          "max-file": "5",
          "max-size": "2m"
        }
      },
      "ports": [
        "127.0.0.1:9200:9200"
      ],
      "ulimits": {
        "memlock": {
          "hard": -1,
          "soft": -1
        }
      },
      "volumes": [
        "esdata:/usr/share/elasticsearch/data",
        "./docker/elasticsearch/roles.yml:/usr/share/elasticsearch/config/roles.yml",
        "./docker/elasticsearch/users:/usr/share/elasticsearch/config/users",
        "./docker/elasticsearch/users_roles:/usr/share/elasticsearch/config/users_roles"
      ]
    },
    "kibana": {
      "container_name": "localtesting_7.12.0_kibana",
      "depends_on": {
        "elasticsearch": {
          "condition": "service_healthy"
        }
      },
      "environment": {
        "ELASTICSEARCH_HOSTS": "http://elasticsearch:9200",
        "ELASTICSEARCH_PASSWORD": "changeme",
        "ELASTICSEARCH_USERNAME": "kibana_system_user",
        "SERVER_HOST": "0.0.0.0",
        "SERVER_NAME": "kibana.example.org",
        "STATUS_ALLOWANONYMOUS": "true",
        "TELEMETRY_ENABLED": "false",
        "XPACK_APM_SERVICEMAPENABLED": "true",
        "XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY": "fhjskloppd678ehkdfdlliverpoolfcr",
        "XPACK_FLEET_AGENTS_ELASTICSEARCH_HOST": "http://elasticsearch:9200",
        "XPACK_FLEET_AGENTS_KIBANA_HOST": "http://kibana:5601",
        "XPACK_FLEET_AGENTS_TLSCHECKDISABLED": "true",
        "XPACK_MONITORING_ENABLED": "true",
        "XPACK_SECURITY_ENCRYPTIONKEY": "fhjskloppd678ehkdfdlliverpoolfcr",
        "XPACK_SECURITY_LOGINASSISTANCEMESSAGE": "Login&#32;details:&#32;`admin/changeme`.&#32;Further&#32;details&#32;[here](https://github.com/elastic/apm-integration-testing#logging-in).",
        "XPACK_XPACK_MAIN_TELEMETRY_ENABLED": "false"
      },
      "healthcheck": {
        "interval": "10s",
        "retries": 20,
        "test": [
          "CMD",
          "curl",
          "--write-out",
          "'HTTP %{http_code}'",
          "-k",
          "--fail",
          "--silent",
          "--output",
          "/dev/null",
          "http://kibana:5601/api/status"
        ]
      },
      "image": "docker.elastic.co/kibana/kibana:7.12.0",
      "labels": [
        "co.elastic.apm.stack-version=7.12.0"
      ],
      "logging": {
        "driver": "json-file",
        "options": {
          "max-file": "5",
          "max-size": "2m"
        }
      },
      "ports": [
        "127.0.0.1:5601:5601"
      ]
    },
    "opbeans-dotnet": {
      "image": "opbeans/opbeans-dotnet:latest",
      "container_name": "localtesting_7.12.0_opbeans-dotnet",
      "depends_on": {
        "apm-server": {
          "condition": "service_healthy"
        },
        "elasticsearch": {
          "condition": "service_healthy"
        }
      },
      "environment": [
        "ELASTIC_APM_SERVICE_NAME=opbeans-dotnet",
        "ELASTIC_APM_SERVICE_VERSION=None",
        "ELASTIC_APM_SERVER_URLS=http://apm-server:8200",
        "ELASTIC_APM_JS_SERVER_URL=http://apm-server:8200",
        "ELASTIC_APM_VERIFY_SERVER_CERT=false",
        "ELASTIC_APM_FLUSH_INTERVAL=5",
        "ELASTIC_APM_TRANSACTION_MAX_SPANS=50",
        "ELASTIC_APM_TRANSACTION_SAMPLE_RATE=1",
        "ELASTICSEARCH_URL=http://elasticsearch:9200",
        "OPBEANS_DT_PROBABILITY=0.50",
        "ELASTIC_APM_ENVIRONMENT=production",
        "OPBEANS_SERVICES=opbeans-dotnet"
      ],
      "healthcheck": {
        "interval": "10s",
        "retries": 36,
        "test": [
          "CMD",
          "curl",
          "--write-out",
          "'HTTP %{http_code}'",
          "-k",
          "--fail",
          "--silent",
          "--output",
          "/dev/null",
          "http://opbeans-dotnet:80/"
        ]
      },
      "logging": {
        "driver": "json-file",
        "options": {
          "max-file": "5",
          "max-size": "2m"
        }
      },
      "ports": [
        "127.0.0.1:3004:80"
      ]
    },
    "opbeans-load-generator": {
      "container_name": "localtesting_7.12.0_opbeans-load-generator",
      "depends_on": {
        "opbeans-dotnet": {
          "condition": "service_healthy"
        }
      },
      "environment": [
        "WS=1",
        "OPBEANS_URLS=opbeans-dotnet:http://opbeans-dotnet:80",
        "OPBEANS_RPMS=opbeans-dotnet:100"
      ],
      "image": "opbeans/opbeans-loadgen:latest",
      "logging": {
        "driver": "json-file",
        "options": {
          "max-file": "5",
          "max-size": "2m"
        }
      },
      "ports": [
        "8999:8000"
      ]
    },
    "postgres": {
      "container_name": "localtesting_7.12.0_postgres",
      "environment": [
        "POSTGRES_DB=opbeans",
        "POSTGRES_PASSWORD=verysecure"
      ],
      "healthcheck": {
        "interval": "10s",
        "test": [
          "CMD",
          "pg_isready",
          "-h",
          "postgres",
          "-U",
          "postgres"
        ]
      },
      "image": "postgres:10",
      "logging": {
        "driver": "json-file",
        "options": {
          "max-file": "5",
          "max-size": "2m"
        }
      },
      "ports": [
        "5432:5432"
      ],
      "volumes": [
        "./docker/opbeans/sql:/docker-entrypoint-initdb.d",
        "pgdata:/var/lib/postgresql/data"
      ]
    },
    "redis": {
      "command": "--save ''",
      "container_name": "localtesting_7.12.0_redis",
      "healthcheck": {
        "interval": "10s",
        "test": [
          "CMD",
          "redis-cli",
          "ping"
        ]
      },
      "image": "redis:4",
      "logging": {
        "driver": "json-file",
        "options": {
          "max-file": "5",
          "max-size": "2m"
        }
      },
      "ports": [
        "6379:6379"
      ]
    },
    "wait-service": {
      "container_name": "wait",
      "depends_on": {
        "apm-server": {
          "condition": "service_healthy"
        },
        "elasticsearch": {
          "condition": "service_healthy"
        },
        "kibana": {
          "condition": "service_healthy"
        },
        "opbeans-dotnet": {
          "condition": "service_healthy"
        },
        "postgres": {
          "condition": "service_healthy"
        },
        "redis": {
          "condition": "service_healthy"
        }
      },
      "image": "busybox"
    }
  },
  "version": "2.4",
  "volumes": {
    "esdata": {
      "driver": "local"
    },
    "pgdata": {
      "driver": "local"
    }
  }
}
