---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Chart.Name }}-{{ .Values.username }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
spec:
  limits:
  - default:
      cpu: 500m
      memory: 100Mi
    defaultRequest:
      cpu: 0.5
      memory: 50Mi
    type: Container