---
apiVersion: v1
kind: ConfigMap
metadata:
  name: heartbeat-config
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
  labels:
    k8s-app: heartbeat
data:
  heartbeat.yml: |-
    heartbeat.monitors:
    - type: icmp
      schedule: '*/10 * * * * * *'
      name: GitHub
      hosts: ["github.com"]
    - type: http
      schedule: '@every 10s'
      name: GitHub
      urls: ["https://github.com"]
    - type: http
      schedule: '@every 10s'
      name: Elastic
      urls: ["https://www.elastic.co"]
      check.response.status: 200
    heartbeat.autodiscover:
      cleanup_timeout: 10s
      providers:
        - type: kubernetes
          hints.enabled: true
    name: heartbeat
    setup.dashboards.enabled: false
    setup.template.overwrite: true
    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_URL}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      pipeline: enrich-service-names
    processors:
      - add_cloud_metadata:
      - add_docker_metadata:
      - add_observer_metadata:
          cache.ttl: 5m
          geo:
            name: nyc-gcp-us-east1
            location: 40.7128, -74.0060
      - drop_event:
          when:
            not:
              equals:
                kubernetes.namespace: {{ .Chart.Name }}-{{ .Values.username }}
    monitoring:
      enabled: true
      elasticsearch:
        username: ${ELASTICSEARCH_USERNAME}
        password: ${ELASTICSEARCH_PASSWORD}
    setup.ilm.enabled: true
    setup.ilm.policy_file: /etc/ilm_policy.json
    setup.ilm.overwrite: true
  ilm_policy.json: |-
    {
        "policy": {
            "phases": {
                "hot": {
                    "min_age": "0ms",
                    "actions": {
                        "rollover": {
                            "max_age": "6h",
                            "max_size": "20gb"
                        }
                    }
                },
                "delete": {
                    "min_age": "2d",
                    "actions": {
                        "delete": {}
                    }
                }
            }
        }
    }
