---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: heartbeat-{{ .Chart.Name }}-{{ .Values.username }}
subjects:
- kind: ServiceAccount
  name: heartbeat-{{ .Chart.Name }}-{{ .Values.username }}
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
roleRef:
  kind: ClusterRole
  name: heartbeat-{{ .Chart.Name }}-{{ .Values.username }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: heartbeat-{{ .Chart.Name }}-{{ .Values.username }}
  labels:
    k8s-app: heartbeat
rules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - events
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - deployments
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heartbeat-{{ .Chart.Name }}-{{ .Values.username }}
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
  labels:
    k8s-app: heartbeat-{{ .Chart.Name }}-{{ .Values.username }}