---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat-daemonset
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
  labels:
    k8s-app: filebeat
    app: beat
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
        app: beat
    spec:
      {{- template "affinity" . }}
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:{{ .Values.stack_version }}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
           cpu: 300m
           memory: 505Mi
          requests:
           cpu: 50m
           memory: 50Mi
        args: [
          "-c", "/etc/filebeat.yml"
        ]
        env:
        - name: ELASTICSEARCH_USERNAME
          value: "admin"
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-es-creds
              key: ELASTICSEARCH_PASSWORD
        - name: ELASTICSEARCH_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-es-creds
              key: ELASTICSEARCH_URL
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: config
          mountPath: /etc/ilm_policy.json
          readOnly: true
          subPath: ilm_policy.json
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlog
          mountPath: /var/log
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: filebeat-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: data
        emptyDir: {}