---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
  labels:
    app: redis
data:
  redis.conf: |-
    slowlog-log-slower-than 0
    loglevel notice