---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis