---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice-1.6
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
  labels:
    app: cartservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
      annotations:
        co.elastic.monitor/type: tcp
        co.elastic.monitor/name: cartservice-{{ .Values.username }}
        co.elastic.monitor/hosts: ${data.host}:11000
        co.elastic.monitor/schedule: "@every 10s"
        co.elastic.monitor/timeout: 1s
        co.elastic.logs/enabled: "true"
        co.elastic.logs/json.keys_under_root: "true"
        co.elastic.logs/processors.add_fields.target: "service"
        co.elastic.logs/processors.add_fields.fields.name: "cartService"
        eden.core_infra: "true"
    spec:
      {{- template "affinity" . }}
      imagePullSecrets:
        - name: elastic-prod-registry
      containers:
      - name: cartservice
        image: 259473336658.dkr.ecr.ap-south-1.amazonaws.com/ntt-poc-cartservice:v1
        imagePullPolicy: IfNotPresent
        readinessProbe:
          tcpSocket:
            port: 11000
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 5m
            memory: 50Mi
        env:
        - name: REDIS_ADDR
          value: "redis:6379"
        - name: SLOW_TOGGLE
          value: "False"
        - name: ELASTIC_APM_LOG_LEVEL
          value: "INFO"
        - name: PORT
          value: "11000"
        - name: ELASTIC_APM_SERVICE_VERSION
          value: "1.6"
        - name: ELASTIC_APM_SERVICE_NAME
          value: "cartService"
        - name: ELASTIC_APM_SERVER_URLS
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-apm-creds
              key: APM_URL
        - name: ELASTIC_APM_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-apm-creds
              key: APM_SECRET_TOKEN
        - name: ELASTIC_APM_ENVIRONMENT
          value: "prod"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice-1.7
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
  labels:
    app: cartservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
      annotations:
        co.elastic.monitor/type: tcp
        co.elastic.monitor/name: cartservice-{{ .Values.username }}
        co.elastic.monitor/hosts: ${data.host}:11000
        co.elastic.monitor/schedule: "@every 10s"
        co.elastic.monitor/timeout: 1s
        co.elastic.logs/enabled: "true"
        co.elastic.logs/json.keys_under_root: "true"
        co.elastic.logs/processors.add_fields.target: "service"
        co.elastic.logs/processors.add_fields.fields.name: "cartService"
        eden.core_infra: "true"
    spec:
      {{- template "affinity" . }}
      imagePullSecrets:
        - name: elastic-prod-registry
      containers:
      - name: cartservice
        image: docker.elastic.co/sa/{{ .Chart.Name }}-cartservice:{{ .Values.es_version }}-{{ .Values.build_num }}
        imagePullPolicy: IfNotPresent
        readinessProbe:
          tcpSocket:
            port: 11000
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 10m
            memory: 50Mi
        env:
        - name: REDIS_ADDR
          value: "redis:6379"
        - name: SLOW_TOGGLE
          value: "True"
        - name: ELASTIC_APM_LOG_LEVEL
          value: "INFO"
        - name: PORT
          value: "11000"
        - name: ELASTIC_APM_SERVICE_VERSION
          value: "1.7"
        - name: ELASTIC_APM_SERVICE_NAME
          value: "cartService"
        - name: ELASTIC_APM_SERVER_URLS
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-apm-creds
              key: APM_URL
        - name: ELASTIC_APM_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-apm-creds
              key: APM_SECRET_TOKEN
        - name: ELASTIC_APM_ENVIRONMENT
          value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
  labels:
    app: cartservice
spec:
  clusterIP: 'None'
  ports:
  - port: 11000
    targetPort: 11000
  selector:
    app: cartservice