---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
  labels:
    app: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
      annotations:
        co.elastic.monitor/type: tcp
        co.elastic.monitor/name: paymentservice-{{ .Values.username }}
        co.elastic.monitor/hosts: ${data.host}:5000
        co.elastic.monitor/schedule: "@every 10s"
        co.elastic.monitor/timeout: 1s
        co.elastic.logs/enabled: "true"
        co.elastic.logs/json.keys_under_root: "true"
        co.elastic.logs/processors.add_fields.target: "service"
        co.elastic.logs/processors.add_fields.fields.name: "paymentService"
        eden.core_infra: "true"
    spec:
      {{- template "affinity" . }}
      imagePullSecrets:
        - name: elastic-prod-registry
      containers:
      - name: paymentservice
        image: docker.elastic.co/sa/{{ .Chart.Name }}-paymentservice:{{ .Values.es_version }}-{{ .Values.build_num }}
        imagePullPolicy: IfNotPresent
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
           cpu: 200m
           memory: 100Mi
          requests:
           cpu: 10m
           memory: 35Mi
        env:
        - name: PORT
          value: "5000"
        - name: ELASTIC_APM_SERVICE_VERSION
          value: "1.7"
        - name: ELASTIC_APM_SERVICE_NAME
          value: "paymentService"
        - name: ELASTIC_APM_SERVER_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-apm-creds
              key: APM_URL
        - name: ELASTIC_APM_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-apm-creds
              key: APM_SECRET_TOKEN
        - name: ELASTIC_APM_ENVIRONMENT
          value: "prod"
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: paymentservice-2
#  namespace: {{ .Chart.Name }}-{{ .Values.username }}
#  labels:
#    app: paymentservice
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: paymentservice
#  template:
#    metadata:
#      labels:
#        app: paymentservice
#      annotations:
#        co.elastic.monitor/type: tcp
#        co.elastic.monitor/name: paymentservice-{{ .Values.username }}
#        co.elastic.monitor/hosts: ${data.host}:5000
#        co.elastic.monitor/schedule: "@every 10s"
#        co.elastic.monitor/timeout: 1s
#        co.elastic.logs/enabled: "true"
#        co.elastic.logs/json.keys_under_root: "true"
#        co.elastic.logs/processors.add_fields.target: "service"
#        co.elastic.logs/processors.add_fields.fields.name: "paymentService"
#        eden.core_infra: "true"
#    spec:
#      imagePullSecrets:
#        - name: elastic-prod-registry
#      containers:
#      - name: paymentservice
#        image: docker.elastic.co/sa/{{ .Chart.Name }}-paymentservice:{{ .Values.es_version }}-{{ .Values.build_num }}
#        imagePullPolicy: IfNotPresent
#        readinessProbe:
#          tcpSocket:
#            port: 5000
#          initialDelaySeconds: 10
#          periodSeconds: 5
#        resources:
#          limits:
#           cpu: 50m
#           memory: 100Mi
#          requests:
#           cpu: 5m
#           memory: 50Mi
#        env:
#        - name: ELASTIC_APM_SECRET_TOKEN
#          value: "hsGeMR7x7vLu8g5G5i"
#        - name: PORT
#          value: "5000"
#        - name: ELASTIC_APM_SERVICE_VERSION
#          value: "1.7"
#        - name: ELASTIC_APM_SERVICE_NAME
#          value: "paymentService"
#        - name: ELASTIC_APM_SERVER_URL
#          value: "http://apm-server:8200"
#        - name: ELASTIC_APM_ENVIRONMENT
#          value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
  labels:
    app: paymentservice
spec:
  clusterIP: 'None'
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: paymentservice