---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
  labels:
    app: productcatalogservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
      annotations:
        co.elastic.monitor/type: tcp
        co.elastic.monitor/name: productcatalogservice-{{ .Values.username }}
        co.elastic.monitor/hosts: ${data.host}:9000
        co.elastic.monitor/schedule: "@every 10s"
        co.elastic.monitor/timeout: 1s
        co.elastic.logs/enabled: "true"
        co.elastic.logs/json.keys_under_root: "true"
        co.elastic.logs/processors.add_fields.target: "service"
        co.elastic.logs/processors.add_fields.fields.name: "productCatalogService"
        eden.core_infra: "true"
    spec:
      {{- template "affinity" . }}
      imagePullSecrets:
        - name: elastic-prod-registry
      containers:
      - name: productcatalogservice
        image: docker.elastic.co/sa/{{ .Chart.Name }}-productcatalogservice:{{ .Values.es_version }}-{{ .Values.build_num }}
        imagePullPolicy: IfNotPresent
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
           cpu: 50m
           memory: 100Mi
          requests:
           cpu: 5m
           memory: 30Mi
        env:
        - name: PORT
          value: "9000"
        - name: ELASTIC_APM_SERVICE_VERSION
          value: "2.2"
        - name: ELASTIC_APM_SERVICE_NAME
          value: "productCatalogService"
        - name: ELASTIC_APM_SERVER_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-apm-creds
              key: APM_URL
        - name: ELASTIC_APM_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-apm-creds
              key: APM_SECRET_TOKEN
        - name: ELASTIC_APM_ENVIRONMENT
          value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
  labels:
    app: productcatalogservice
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: productcatalogservice


